version: "3"
services:
  node:
    restart: always
    build:
      context: ./
    environment:
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "4013:3000"
    container_name: reactivers-backend2
